# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
#       Symfony\Component\Security\Core\User\User: plaintext
        Brdeju\Bundle\CurrenciesChartsBundle\Entity\User: 
            algorithm: sha256
            encode_as_base64: true
            iterations: 1      

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        
    providers:
        users:
            entity: { class: CurrenciesChartsBundle:User }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/(login$|register)$
            security: false
            
        secured_area:
            pattern:    ^/
            form_login:
                check_path: check_path
                login_path: login_path
                always_use_default_target_path: false
                default_target_path: currencies
            logout:
                path:   _logout
                target: login_path
            remember_me:
                key:      "%secret%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ 